### ISSUE TITLE
fix: absolute paths error on windows

### ISSUE THREAD

**Issue by AndreasKubasa** [dargmuesli/nuxt-cookie-control#14]
The issue when you add @dargmuesli/nuxt-cookie-control to the modules section of nuxt.config.ts

Cannot start nuxt:  Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'        

  at new NodeError (node:internal/errors:371:5)
  at defaultResolve (node:internal/modules/esm/resolve:1016:11)
  at ESMLoader.resolve (node:internal/modules/esm/loader:422:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:222:40)
  at ESMLoader.import (node:internal/modules/esm/loader:276:22)
  at importModuleDynamically (node:internal/modules/esm/translators:111:35)
  at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)
  at loadLocales (/C:/Users/akubasa/workspace/nuxt-app/node_modules/@dargmuesli/nuxt-cookie-control/dist/module.mjs:175:31)
  at async setup (/C:/Users/akubasa/workspace/nuxt-app/node_modules/@dargmuesli/nuxt-cookie-control/dist/module.mjs:101:5)
  at async normalizedModule (/C:/Users/akubasa/workspace/nuxt-app/node_modules/@nuxt/kit/dist/index.mjs:167:5)
  at async installModule (/C:/Users/akubasa/workspace/nuxt-app/node_modules/@nuxt/kit/dist/index.mjs:416:3)
  at async initNuxt (/C:/Users/akubasa/workspace/nuxt-app/node_modules/nuxt/dist/index.mjs:1825:7)
  at async load (/C:/Users/akubasa/workspace/nuxt-app/node_modules/nuxi/dist/chunks/dev.mjs:6779:9)
  at async Object.invoke (/C:/Users/akubasa/workspace/nuxt-app/node_modules/nuxi/dist/chunks/dev.mjs:6840:5)
  at async _main (/C:/Users/akuba

**Comment by dargmuesli** [comment]
Thank you for reporting that issue. I currently do not have a Windows installation at hand, so whoever feels like submitting a PR is welcome to do so!

**Comment by dargmuesli** [comment]
cc https://github.com/nuxt-community/robots-module/issues/86

**Comment by dargmuesli** [comment]
@AndreasKubasa would you mind to check if #22 fixes the issue for you?

**Comment by AndreasKubasa** [comment]
> @AndreasKubasa would you mind to check if #22 fixes the issue for you?

to be honest, I tested, but now it throws couple more other errors,  so clearly changes something, I guess we need to trust :)

**Comment by dargmuesli** [comment]
Throwing a couple more errors is not necessarily a qualification for a merge, I reckon 😅😂 I'd merge it once I get feedback by the PR creator to open questions.

**Comment by diasconmagia** [comment]
PR #22 doesn't work for me either. Has anyone been able to fix it?

**Comment by oscarvadillog** [comment]
PR #22 doesn't work for me either. Has anyone been able to fix it?

**Comment by dargmuesli** [comment]
Upstream issue: https://github.com/nuxt/nuxt/issues/15500

**Comment by dargmuesli** [comment]
Would you guys please try `nuxt v3.2.3` with `@dargmuesli/nuxt-cookie-module v5.0.1` and report if fixes in those releases resolve this issue?

**Comment by dargmuesli** [comment]
Also, thx @mshadowz for providing a workaround!

**Comment by ennioVisco** [comment]
> Also, thx @mshadowz for providing a workaround!

I suggest you re-enable Windows here: https://github.com/dargmuesli/nuxt-cookie-control/blob/5a1742bfe05eda59139d8caf9333c01df08c529d/.github/workflows/ci.yml#L13

since https://github.com/nuxt/nuxt/issues/15249 has been resolved!

**Comment by dargmuesli** [comment]
Please try `v5.0.2` once released and report if the issue is resolved :)

**Comment by r-modica-cti** [comment]
This package still doesn't work with windows it seems, it is unable to resolve the module when you include it
